export enum Bank {
  UNION_BANK = 'UNION_BANK',
  BANKO_DE_ORO = 'BANKO_DE_ORO',
  PHILIPPINE_NATIONAL_BANK = 'PHILIPPINE_NATIONAL_BANK',
  SECURITY_BANK = 'SECURITY_BANK',
  ROBINSONS_BANK_CORPORATION = 'ROBINSONS_BANK_CORPORATION',
}
